server {
    listen 8080;
    host localhost;

    root ./www;
    index index.html;

    location /images {
        root ./static;
    }

    location /upload {
        methods POST;
        upload_dir ./uploads;
    }

    location /cgi-bin {
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}